### ISSUE TITLE
Remove user/ID variations for Slash Commands

### ISSUE THREAD

**Issue by PlavorSeol** [botlabs-gg/yagpdb#1007]
Most of Slash Commands which accepts an user as an option have 2 subcommand variations: `by-user` and `by-user-id`. This requires more typing and therefore is inconvenient compared to regular commands.
Some others (`/automod logs`, `/clean`, etc.) have both `user` and `user-id` options which are optional.

I don't see the point of separating command or option for user and ID, as it unnecessarily complicates user experience.
It is already possible to use ID for user-type option. For example, `/ban by-user user:105487308693757952 reason:Added unnecessary subcommands to Slash Commands` works perfectly fine.
So why should we have separate subcommand or option for ID with string-type option? We should remove them and just use user-type option.

**Comment by JordiHakimZiyech** [comment]
I am pretty sure Jonas had a reason for this, I think it had to do with how discord handles slash commands. But i'm not sure whether this is still necessary, so you'd have to ask him

**Comment by Wolveric** [comment]
I didn't realise that worked, and that's entirely unintuitive... as sub-commands, and with the broader limits now on slash command counts though, I'd honestly prefer to keep them, simply for that reason alone...

**Comment by PlavorSeol** [comment]
@Wolveric I really don't understand your sentence as a whole.

> I didn't realise that worked

Yes, of course it clearly works. Why not?

> and that's entirely unintuitive...

What are you saying is "entirely unintuitive"? Do you mean Discord accepting ID for user-type option? Or current Slash Commands which are diverged into 2 separate subcommands?

> as sub-commands, and with the broader limits now on slash command counts though, I'd honestly prefer to keep them, simply for that reason alone...

This is nothing to do with current top-level commands limit. Since this effectively means removing `by-user` and `by-user-id` subcommands and just using top-level command instead, the result for top-level commands quota should be exactly same.

**Comment by Wolveric** [comment]
> Yes, of course it clearly works. Why not?
Because slash commands run a level of argument checking, which, when using a user argument, involves Discord bringing up a list of users in the server, along with inserting an `@` on mobile.

This lead to an assumption, that entering an ID wouldn't be a valid argument, and presumably ended up with `user-id` variants. It never crossed my mind, because that's not an intuitive presentation.

As for he limits, I'm not entirely familiar with how they interact, but I'm aware there's a 25 sub-command limit, per-layer, which YAGPDB isn't even approaching in any case...

**Comment by PlavorSeol** [comment]
> Because slash commands run a level of argument checking, which, when using a user argument, involves Discord bringing up a list of users in the server, along with inserting an @ on mobile.
>
> This lead to an assumption, that entering an ID wouldn't be a valid argument, and presumably ended up with user-id variants. It never crossed my mind, because that's not an intuitive presentation.

See discord/discord-api-docs#2449.

Discord supports using IDs for channel, role and user-type options since January 28, 2021. [Work](https://github.com/jonas747/yagpdb/pull/878) for implementing Slash Commands in YAGPDB was started at April 28, 2021, so it was a thing for 3 months at that time.

While I'm not sure if most users will think 2 separate subcommands for user and ID are "intuitive", I still can say for sure that using `/ban by-user` is much more inconvenient than typing `/`, `b`, `a`, `n`, `(space or tab)`. We didn't have variations for regular commands which enforces using ID instead of mention, right? (I know there is `-banid` command, but since it also works with mentions, it is effectively just an alias for `-ban`.)

Not only Discord supports using IDs for some types of options, but they also validates the type of Snowflake ID used as a value on the Discord-side. This means if you put a role ID to user-type option, Discord will throw an error rather than sending an interaction to YAGPDB. Since `by-user-id` subcommands use string-type option, they lack the benefit of Discord-side validation. I don't think we should bypass this kind of validation, or do we?

**Comment by Wolveric** [comment]
The fact no regular, or even more involved, user, has contested this implementation up until this point, goes to show not everyone reads that deeply into the docs... 

If this was more widely known information, not just among those who need to use that level of attention while developing bots of their own, this would've been more reasonable initially. But now it's been a staple implementation, I more likely foresee this simply creating a landslide of confused users, enquiring on why this was changed... as being able to use an ID value, for an argument named "user", presented as a user list, with an `@` in the text field, is _not_ an intuitive presentation...

**Comment by PlavorSeol** [comment]
Good for you dude, botlabs-gg/dcmd#4 finally implemented this, which you were calling as your so-called "unintuitive". So cry harder lol 🤣
