### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by liamf1994** [botlabs-gg/yagpdb#1087]
Server verification is too low

**Comment by BlackWolfWoof** [comment]
What?

**Comment by liamf1994** [comment]
For your server it's saying verification level is too high for me to join when I click accept number goes up them straight back down

**Comment by BlackWolfWoof** [comment]
Why write that on GitHub then...
My nickname on Discord literally says "Can't verify? Dm me"

**Comment by ashishjh-bst** [comment]
Bug is for discord, please DM admins for manual verification for now.
