### ISSUE TITLE
Detect URLs through top level domains

### ISSUE THREAD

**Issue by Timmeey86** [botlabs-gg/yagpdb#1116]
I'm often getting my messages removed in a server where I don't have access to the yagpdb bot configuration, when I ask people what their `whatever.log` contains, or navigate them to `somefile.exe`.
Would it maybe be possible to block only those URLs which contain an actual top level domain as defined in [this list](https://en.wikipedia.org/wiki/List_of_Internet_top-level_domains) for example?
Dependent on what your current code looks like it might need an additional filter for IP addresses possibly

**Comment by ashishjh-bst** [comment]
I believe it already doable and this is an issue with your config. 

The github repo is not for support with the bot, please ask for it in the support server.
