### ISSUE TITLE
Couldn't find Menu for Role Menu that exists

### ISSUE THREAD

**Issue by mstan** [botlabs-gg/yagpdb#1117]
Hi,

I am attempting to update a rolemenu in my server and whenever I try to, I get the message "Couldn't find menu" from the bot.

I have two role based menus in my server. One is for Games. The other is for Streams. The streams menu can be updated with no issue. Only the Games one returns the "Couldn't find menu" message.

The message ID for the games one is `867112035670294568`. The server is "VictoryPit". I'm happy to provide an invite link for any developers who need access in order to debug (if necessary).

**Comment by jo3-l** [comment]
Hello; generally speaking issues with the bot should be brought up in the [support server](discord.gg/4udtcA5) first, as there's more people available to help there.

With that said, I suggest checking that you are running the command in the channel the target message is posted in, in addition to ensuring that the rolemenu attached to the message actually works (i.e., it has not been removed via `rolemenu remove` in the meantime.)

**Comment by ashishjh-bst** [comment]
Closed because this is something related to the Bot and not YAGPDB project.
