### ISSUE TITLE
Suggestion: noDM flag for the kick and ban action

### ISSUE THREAD

**Issue by k3rnelpan1c-dev** [botlabs-gg/yagpdb#1132]
Hi all I would like to suggest an additional parameter for the `kick` and `ban` action, that allows moderator/admins/owners to run these actions without triggering a DM to the 'target' of the action.

The idea is sourced from Elemental Bot, which has this kind of option.

As far as I can tell such a change would affect the parameters of the [`punish` function](https://github.com/botlabs-gg/yagpdb/blob/87abc4861393ca17bd0f1d2f56d931b7e8e12eb6/moderation/punishments.go#L52) and its callers.
I may try and provide a PR, however my GOLang knowledge is limited and I don't know when I would have time provide such a patch.

Thank you for consideration and hope I did not miss any similar request/suggestion to this.

**Comment by DunnNDusted** [comment]
If you want to make a suggestion, YAGPDB's [support server](https://discord.gg/4udtcA5) is more appreciate.

**Comment by k3rnelpan1c-dev** [comment]
Thank you for the hint, I may pay the server a visit!
However, I have to admit that I am scratching my head slightly if handling Suggestions/Feature Requests in Discord is better than GitHub issues :sweat_smile: (I realize that I post that on a GitHub repo of a Discord bot)

**Comment by DunnNDusted** [comment]
It's based on a vote system, with a filter. It gives better visibility as a whole, as the server gets more eyes than the GitHub issues.

**Comment by k3rnelpan1c-dev** [comment]
ah, makes sense.
