### ISSUE TITLE
Allow mention @everyone for streaming plugin

### ISSUE THREAD

**Issue by aaronr8684** [botlabs-gg/yagpdb#1133]
Similar to the YouTube notifications, allow for a @everyone mention and maybe even @here

**Comment by ashishjh-bst** [comment]
Post all suggestions in the support server. We don't use the issue tracker here.

**Comment by aaronr8684** [comment]
> This is also already possible.

@DunnNDusted I have tried a few different ways, but it doesn't seem to actually mention the roles. Care to elaborate how you were able to get it working?
