### ISSUE TITLE
Inclusive naming

### ISSUE THREAD

**Issue by jamesgeddes** [botlabs-gg/yagpdb#1183]
On behalf of [Geek.Zone](http://Geek.Zone), a member of The Inclusive Naming Initiative, may I request that YAGPDB migrates to using [inclusive naming](https://inclusivenaming.org/word-lists/tier-1/), please?

Thanks!

**Comment by l-zeuch** [comment]
May I ask what specifically shall be changed?

This is a too vague request as it stands, as it can mean a multitude of things.

**Comment by ashishjh-bst** [comment]
Too vague, if you want specific instances to be changed, please raise a PR.

**Comment by jamesgeddes** [comment]
Too vague? Did you take a moment to read the link that I included?

https://inclusivenaming.org/word-lists/tier-1/

**Comment by jamesgeddes** [comment]
Also, could you ask for clarification before instaclosing a ticket?

**Comment by ashishjh-bst** [comment]
Unnecessary Discussion.   Locking conversation.  If you want something related to grammar and language used in the ticket, Please raise a PR for each instance, also do raise PRs to update the documentation related to said features.
