### ISSUE TITLE
Inclusive naming

### ISSUE THREAD

**Issue by jamesgeddes** [botlabs-gg/yagpdb#1185]
May I request that YAGPDB migrates to using inclusive naming, please? 

https://inclusivenaming.org/word-lists/tier-1/

This includes, but is not limited to,
- default branch name
- variable names
- user interface

Thanks

**Comment by l-zeuch** [comment]
Don't spam new issues if old ones were closed with a clear statement.

**Comment by ashishjh-bst** [comment]
Duplicate of https://github.com/botlabs-gg/yagpdb/issues/1184

**Comment by ashishjh-bst** [comment]
Duplicate of the following issue: https://github.com/botlabs-gg/yagpdb/issues/1183
