### ISSUE TITLE
Suggestion: more international "Hot words" for reputation

### ISSUE THREAD

**Issue by S-E-B-123** [botlabs-gg/yagpdb#1199]
Hi, it would be nice if more international hot words could be used for reputation.
for example:

german --> danke
french   --> merci
dutch    --> bedankt

`var thanksRegex = regexp.MustCompile(`(?i)( |\n|^)(thanks?\pP*|danks|ty|thx|danke|merci|bedankt|\+rep|\+ ?\<\@[0-9]*\>)( |\n|$)`)`

**Comment by ashishjh-bst** [comment]
Suggestions are not accepted via github, please add them to our support server.

**Comment by S-E-B-123** [comment]
Ok, but you have to update your CONTRIBUTING.md
`In order to make a suggestion, head to the [issues page](https://github.com/botlabs-gg/yagpdb/issues) and make an issue titled "Suggestion: (name)" and fill out a little description. Please please please, check that this hasn't already been suggested or requested as a PR.`
