### ISSUE TITLE
[BUG] Video will not be detected

### ISSUE THREAD

**Issue by MarkDeuerling** [botlabs-gg/yagpdb#1303]
Hi,
I think there is a bug with the video detection. Because you check the hour first in feed.go line 387 (the safeguard), a new video will not be detected by the following circumstance: If a video is uploaded under 24 hours the hour will be less of the new video and no new video will be detected.

**Comment by ashishjh-bst** [comment]
```
	if time.Since(parsedPublishedAt) > time.Hour {
		// just a safeguard against empty lastVidTime's
		return nil
	}
```

If you're referring to this, then this just checks if the video was uploaded in the last hour, if it was uploaded before that then it ignores it.
