### ISSUE TITLE
Automoderator monitoring tools

### ISSUE THREAD

**Issue by noraj** [botlabs-gg/yagpdb#1309]
## Issue

It would be nice for moderators to have tools to monitor violations.

- [Automoderator v1](https://docs.yagpdb.xyz/tools-and-utilities/automoderator) doesn't have any monitoring options
- [Automoderator v2](https://docs.yagpdb.xyz/tools-and-utilities/automoderator-v2#logs) has a logs tab

While it's nice to have a logs tab on the control panel there is no monitoring features on the discord server itself.

## Feature 1 : notification channel

Other moderation bots like [MEE6](https://mee6.xyz/plugins/management) have a feature to report any violation in a channel so moderators can receive notifications on discord directly and all violations logged on a channel.

![image](https://user-images.githubusercontent.com/16578570/183269170-39d91420-3b51-4e2d-95ae-6e87c013ac1f.png)

![image](https://user-images.githubusercontent.com/16578570/183269277-3b92bb08-9964-4f52-b6f1-394ce95ada81.png)

The idea would be that for each [moderation tool](https://docs.yagpdb.xyz/tools-and-utilities/moderation) and for all rules of Automoderator v1 and Automoderator v2 having dropdown button to select a notification channel.

![image](https://user-images.githubusercontent.com/16578570/183269247-e401ba73-56e9-403b-ab8a-b6b513e413b0.png)

## Feature 2 : moderation logs commands

There is already [automod Logs](https://docs.yagpdb.xyz/commands/all-commands#automod-logs) but it shows nothing to me while there was violation recently.

![image](https://user-images.githubusercontent.com/16578570/183269543-902893c7-bf88-43e2-9c54-7662f444761a.png)

It says it's a alias of `log` commands but actually the [logs](https://docs.yagpdb.xyz/commands/all-commands#logs) gives a link to a dashboard with all messages on the server, which is not the same thing.

The [automod ListViolations](https://docs.yagpdb.xyz/commands/all-commands#automod-listviolations) command requires a user to work. You can't do stuff like list all violation globally or for a channel or filter for a certain time range (less than 10, lays 24h, last 7 days, etc.)

Also it's not clear if those commands should for for automoderator v1, or v2, or both, or also for manual moderation commands like warnings.

**Comment by l-zeuch** [comment]
Hi, thanks for writing in! However, we use the [support server](https://discord.com/invite/0vYlUK2XBKldPSMY) for suggestions and requests.

Nonetheless, let me address your comment.

Just so we're on the same page: (Automod) violations are not the same as warnings as per your screenshot -- violations are entirely internal to automod v2, meant as a way to track transgressions of tiered rulesets and similar. Thus, notifications for these are (as of now) not emitted, neither in DMs to the offending user nor in any channel.

----
> Feature 1 : notification channel
>
> Other moderation bots like [MEE6](https://mee6.xyz/plugins/management) have a feature to report any violation in a channel so moderators can receive notifications on discord directly and all violations logged on a channel.

Such a feature already exists, called **mod log**. See [here](https://docs.yagpdb.xyz/tools-and-utilities/moderation) for a mention of it and [here](https://yagpdb.xyz/manage/166207328570441728/moderation) for a demonstration on how to set it up.

Additionally, here's a screenshot:
![image](https://user-images.githubusercontent.com/71897876/183286065-3f75f1a2-9cd6-43eb-9cea-0d09ae090749.png)

There are indeed suggestions with regards to having a channel where *violations* are sent to, though.

> The idea would be that for each [moderation tool](https://docs.yagpdb.xyz/tools-and-utilities/moderation) and for all rules of Automoderator v1 and Automoderator v2 having dropdown button to select a notification channel.

1. That is just plain excessive
2. if you *really* want to, you can write some custom command code in the moderation DM field of each respective action

With the above in mind, there's no need to add yet another UI element given that that can already be done via custom commands.

----
>  Feature 2 : moderation logs commands
>
> There is already [automod Logs](https://docs.yagpdb.xyz/commands/all-commands#automod-logs) but it shows nothing to me while there was violation recently.

I think this should be cleared up as per the beginning of my comment. Violations are a wholly different thing, internal to auto-moderation.

> It says it's a alias of log commands but actually the [logs](https://docs.yagpdb.xyz/commands/all-commands#logs) gives a link to a dashboard with all messages on the server, which is not the same thing.

That is not quite correct -- it says it has `log` as an alias, see the attached screenshot:
![image](https://user-images.githubusercontent.com/71897876/183286452-545313ca-48f3-4312-98f0-5e3956702742.png)

> The [automod ListViolations](https://docs.yagpdb.xyz/commands/all-commands#automod-listviolations) command requires a user to work. You can't do stuff like list all violation globally or for a channel or filter for a certain time range (less than 10, lays 24h, last 7 days, etc.)

You can list globally, as per the attached screenshot. The docs were generated at some point and never updated thereafter, or it is a typo.

![image](https://user-images.githubusercontent.com/71897876/183286539-bfe039dd-8228-44cd-baae-27772d3e5b9c.png)

The output of a global server listing would be something like this:
![image](https://user-images.githubusercontent.com/71897876/183286599-116da770-cd42-465b-9b3e-6d49fd6fe7aa.png)

> Also it's not clear if those commands should for for automoderator v1, or v2, or both, or also for manual moderation commands like warnings.

Automod v2 only.

**Comment by noraj** [comment]
>  violations are entirely internal to automod v2
> ...
> I think this should be cleared up as per the beginning of my comment. Violations are a wholly different thing, internal to auto-moderation.

It's was automoderation violations but from automoderator v1 so I guess [automod Logs](https://docs.yagpdb.xyz/commands/all-commands#automod-logs) works only for automod v2.

> You can list globally, as per the attached screenshot. The docs were generated at some point and never updated thereafter, or it is a typo.

That's [automod ListViolationsCount](https://docs.yagpdb.xyz/commands/all-commands#automod-listviolationscount) not [automod ListViolations](https://docs.yagpdb.xyz/commands/all-commands#automod-listviolations).

Thanks for the detailed answers.

**Comment by noraj** [comment]
Summary :

- Feature 1 : notification channel
  - Already exists for kicks and bans
  - [Feature request] for automod v2 violations
- Feature 2 : moderation logs commands
  - It's normal [automod Logs](https://docs.yagpdb.xyz/commands/all-commands#automod-logs) showed me nothing as it was automod v1 violations and the command works only for automod v2 (my PR to clarify this on the doc https://github.com/botlabs-gg/yagpdb-docs/pull/3)
  - [automod ListViolationsCount](https://docs.yagpdb.xyz/commands/all-commands#automod-listviolationscount) can work globally but [automod ListViolations](https://docs.yagpdb.xyz/commands/all-commands#automod-listviolations) doesn't work globally
  - [feature request] to make [automod ListViolations](https://docs.yagpdb.xyz/commands/all-commands#automod-listviolations) works globally
  - `automod ListViolationsCount` has a duration - max violation age but not `automod ListViolations`
  - [feature request] to make `automod ListViolations` have a max age duration filter option
