### ISSUE TITLE
Automoderator v2: output without automoderator: prefix

### ISSUE THREAD

**Issue by MisterMountain** [botlabs-gg/yagpdb#1350]
Hi,

it would be nice if automoderator v2 could post messages triggered by a regex without the Automoderator prefix.
I am using YAGPDB for custom fun responses in a channel and for me the automoderator prefix doesnt have a benefit. Some "correct usages" of the Feature would also benefit, as i want to create automod-rules for violations with an completely custom output

Regards

**Comment by ashishjh-bst** [comment]
You can always mod the code and self-host, won't be done in YAGPDB.
