### ISSUE TITLE
yagpdb problems

### ISSUE THREAD

**Issue by stxrlite** [botlabs-gg/yagpdb#1353]
dont know if i am supposed to post this here but trying to get yagpdb self hosted using this [guide](https://hostyagpdb.xyz/selfhost/selfhostyag) not dokerised on ubuntu 22.04 and use the seperate command "./yagpdb -all -pa -https=false" and when I use it it gives me a error 
![image](https://user-images.githubusercontent.com/78002427/192779646-b44ee89c-73f1-497c-92a0-8ea272128bae.png)

**Comment by ashishjh-bst** [comment]
Closing we don't use the issue tracker here for helping people self host. If yoh have issues feel free to join the support server and ask in the selfhosting discussion.
