### ISSUE TITLE
So I continuosily get this error when running

### ISSUE THREAD

**Issue by TrissieTheHusky** [botlabs-gg/yagpdb#725]
When attempting to run the bot I get 
I have made sure of all the configuration being correct. I am unsure of exactly what the env file's name is suppose to be. I have no idea what so ever. If someone could help me it would really be appreciated.
```
INFO Starting YAGPDB version unknown
INFO Set redis pool size to 10  p=common stck="common.connectRedis:common.go:197"
FATA Failed running core init  stck="run.Init:run.go:104" error="Did not set required config option: \"yagpdb.clientid\" (YAGPDB_CLIENTID as env var)"
```

**Comment by TrissieTheHusky** [comment]
Can Someone Please help? I'm asking a question of what am I suppose to name the config file for the bot. The example .env file

**Comment by ironbelly** [comment]
Seeing this too

**Comment by mpdmonster2** [comment]
I also get this

**Comment by TrissieTheHusky** [comment]
So CLIENT_ID possibly could have forgotten to put the client Id I’mma look into this more

**Comment by TrissieTheHusky** [comment]
I have gained more knowledge about stuff so, I’m look into it more

**Comment by tristencrp** [comment]
Any findings?

**Comment by Pedro-Pessoa** [comment]
Error is pretty explicit. The client ID for the bot has not been set as an env var.

**Comment by TrissieTheHusky** [comment]
It’s Becuase of a docker config error
