### ISSUE TITLE
(Suggestion/Issue) Of Bringing Out On Boarding? for Self Hosters?

### ISSUE THREAD

**Issue by ThunderM16** [botlabs-gg/yagpdb#947]
Wondering if you guys would be so kind to ether 1 push the beta.yagpdb.xyz/onboarding/#ServerID Beautifulity crafted script out from beta to alpha? I'm doing quite a bit of work myself on rethemeing and chaning my clone to my needed additions and would love an amazing Onboarding setup ive hunted and hunted for these files with no luck or am i blind? 

Im currently using `docker-compose -f yagpdb/yagpdb_docker/docker-compose.dev.yml up` to run it so idk if this can be done with the dev setup....

**Comment by shk8s** [comment]
is this possible?

**Comment by shk8s** [comment]
thhis issue is still not been addressed ive been waiting a very long time to find out!

**Comment by Wolveric** [comment]
FYI: Alpha would be a regression...

Plus, from what I understand, the onboarding pages are not part of YAGPDB's open source code-base, as with the UI in general.

In addition: Jonas is on holiday at the time of writing this...

**Comment by ashishjh-bst** [comment]
Onboarding has been shut, and most likely won't be revived.

**Comment by ThunderM16** [comment]
> Onboarding has been shut, and most likely won't be revived.

Can a hint towards how it was accomplished be explained a bit more or as botlabs is killing onboarding from yagpdb official can you release the onboarding requirement configuration + files and or source - Also @ashishjh-bst i believe you are a owner in botlabs.gg so i do want to ask another thing https://gawesomebot.com/ used to be in alot of servers but the devs killed the bot which is sad i brought it back with out any issues or flak from Gilbert - https://github.com/GAwesomeBot/bot and well im wondering if i could get some help when time is well you know more available to you guys as you of course have yagpdb and a few other bots to take care of - not asking for hosting i can handle hosting just fine - but am asking for help on development on some commands that were never worked on and brining the bots code up to par more
